export interface User {
    _id?: number,
    firstName: string,
    lastName: string,
    email: string,
    phoneNumber: string,
    whatsappNumber: string,
    occupation: string,
    organization: string,
    dateOfBirth: string,
    residence: string,
    picture: string,
    hometown: string,
    password?: string,
} 